version: "3.9"
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=zootable
      - POSTGRES_USER=zootable
      - POSTGRES_PASSWORD=zootable
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command:
      - /bin/bash
      - -c
      - |
        python manage.py migrate --noinput
        gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --log-file -
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
    env_file:
      - ./.env
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - db

volumes:
  postgres_data:
