# Generated by Django 2.2.1 on 2019-05-26 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('accession_number', models.PositiveIntegerField()),
                ('identifier', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('exhibits', models.ManyToManyField(to='zoo_checks.Exhibit')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesExhibitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_val', models.PositiveSmallIntegerField(default=0)),
                ('count_date', models.DateTimeField()),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_checks.Exhibit')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_checks.Species')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_val', models.PositiveSmallIntegerField(default=0)),
                ('count_date', models.DateTimeField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_checks.Animal')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='exhibit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_checks.Exhibit'),
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_checks.Species'),
        ),
    ]
