# Generated by Django 2.2.1 on 2019-05-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='name',
            new_name='common_name',
        ),
        migrations.AddField(
            model_name='species',
            name='latin_name',
            field=models.CharField(default='species name default', max_length=80),
            preserve_default=False,
        ),
    ]
