# Generated by Django 2.2.1 on 2019-06-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0002_auto_20190528_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalcount',
            old_name='count_date',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='speciesexhibitcount',
            old_name='count_val',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='speciesexhibitcount',
            old_name='count_date',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='animalcount',
            name='count_val',
        ),
        migrations.AddField(
            model_name='animalcount',
            name='condition',
            field=models.CharField(choices=[('SE', 'seen'), ('NA', 'Needs Attention'), ('BA', 'BAR (Sr. Avic.)'), ('MI', 'Missing (Avic. only)')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='animal',
            name='exhibit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='zoo_checks.Exhibit'),
        ),
        migrations.AlterField(
            model_name='species',
            name='exhibits',
            field=models.ManyToManyField(related_name='species', to='zoo_checks.Exhibit'),
        ),
    ]
