# Generated by Django 2.2.1 on 2019-06-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0003_auto_20190601_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalcount',
            name='condition',
            field=models.CharField(blank=True, choices=[('', ''), ('SE', 'seen'), ('NA', 'Needs Attention'), ('BA', 'BAR (Sr. Avic.)'), ('MI', 'Missing (Avic. only)')], default='', max_length=2),
        ),
    ]
