# Generated by Django 2.2.1 on 2019-06-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0004_auto_20190606_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalcount',
            name='datetimecounted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='speciescount',
            name='datetimecounted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
