# Generated by Django 2.2.1 on 2019-06-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0006_auto_20190606_0434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalcount',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='speciescount',
            old_name='user',
            new_name='users',
        ),
    ]
