# Generated by Django 2.2.2 on 2019-06-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0009_auto_20190607_1744_squashed_0011_auto_20190607_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupcount',
            old_name='count',
            new_name='count_female',
        ),
        migrations.RemoveField(
            model_name='species',
            name='exhibits',
        ),
        migrations.AddField(
            model_name='group',
            name='population_female',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='population_male',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='population_unknown',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupcount',
            name='count_male',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupcount',
            name='count_unknown',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='animal',
            name='accession_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='accession_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
