# Generated by Django 2.2.2 on 2019-06-10 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0015_auto_20190609_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enclosure',
            old_name='user',
            new_name='users',
        ),
    ]
