# Generated by Django 2.2.2 on 2019-06-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0016_auto_20190609_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalcount',
            name='datecounted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='groupcount',
            name='datecounted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='speciescount',
            name='datecounted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
