# Generated by Django 2.2.1 on 2019-06-02 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0001_squashed_0006_auto_20190602_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalcount',
            name='exhibit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zoo_checks.Exhibit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='species',
            name='latin_name',
            field=models.CharField(max_length=80),
        ),
    ]
