# Generated by Django 3.0.8 on 2020-07-25 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    replaces = [
        ("zoo_checks", "0012_auto_20190609_0013"),
        ("zoo_checks", "0013_auto_20190609_1529"),
        ("zoo_checks", "0014_auto_20190609_2157"),
        ("zoo_checks", "0015_auto_20190609_2303"),
        ("zoo_checks", "0016_auto_20190609_2337"),
        ("zoo_checks", "0017_auto_20190610_2214"),
        ("zoo_checks", "0018_auto_20190615_2317"),
        ("zoo_checks", "0019_auto_20190616_0012"),
        ("zoo_checks", "0020_auto_20190617_2300"),
        ("zoo_checks", "0021_auto_20190624_1444"),
        ("zoo_checks", "0022_auto_20190625_1006"),
        ("zoo_checks", "0023_auto_20190704_1623"),
        ("zoo_checks", "0024_auto_20190829_2344"),
        ("zoo_checks", "0025_auto_20190907_1613"),
        ("zoo_checks", "0026_auto_20191008_2248"),
        ("zoo_checks", "0027_auto_20191008_2252"),
        ("zoo_checks", "0028_auto_20191216_1528"),
        ("zoo_checks", "0029_animalcount_comment"),
        ("zoo_checks", "0030_auto_20200127_2222"),
        ("zoo_checks", "0031_auto_20200202_2314"),
        ("zoo_checks", "0032_auto_20200203_0000"),
        ("zoo_checks", "0030_auto_20200207_2126"),
        ("zoo_checks", "0033_merge_20200216_2228"),
        ("zoo_checks", "0034_auto_20200219_2316"),
        ("zoo_checks", "0035_auto_20200222_1052"),
        ("zoo_checks", "0036_convert_group_counts"),
        ("zoo_checks", "0037_auto_20200222_1145"),
        ("zoo_checks", "0038_role_slug"),
        ("zoo_checks", "0039_auto_20200724_2335"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zoo_checks", "0011_auto_20190608_2123"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalcount",
            name="condition",
            field=models.CharField(
                choices=[("BA", "BAR"), ("SE", "Seen"), ("NA", "Attn")], max_length=2
            ),
        ),
        migrations.RenameField(
            model_name="species", old_name="latin_name", new_name="species_name",
        ),
        migrations.AddField(
            model_name="species",
            name="genus_name",
            field=models.CharField(default="", max_length=80),
            preserve_default=False,
        ),
        migrations.RenameModel(old_name="Exhibit", new_name="Enclosure",),
        migrations.RenameField(
            model_name="animal", old_name="exhibit", new_name="enclosure",
        ),
        migrations.RenameField(
            model_name="animalcount", old_name="exhibit", new_name="enclosure",
        ),
        migrations.RenameField(
            model_name="group", old_name="exhibit", new_name="enclosure",
        ),
        migrations.RenameField(
            model_name="groupcount", old_name="exhibit", new_name="enclosure",
        ),
        migrations.RenameField(
            model_name="speciescount", old_name="exhibit", new_name="enclosure",
        ),
        migrations.AlterModelOptions(name="group", options={"ordering": ["species"]},),
        migrations.RemoveField(model_name="group", name="name",),
        migrations.RenameField(
            model_name="enclosure", old_name="user", new_name="users",
        ),
        migrations.AlterField(
            model_name="animalcount",
            name="datecounted",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="groupcount",
            name="datecounted",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="speciescount",
            name="datecounted",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelOptions(
            name="group", options={"ordering": ["species__common_name"]},
        ),
        migrations.AlterField(
            model_name="animalcount",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conditions",
                to="zoo_checks.Animal",
            ),
        ),
        migrations.AlterField(
            model_name="groupcount",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counts",
                to="zoo_checks.Group",
            ),
        ),
        migrations.AlterField(
            model_name="speciescount",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counts",
                to="zoo_checks.Species",
            ),
        ),
        migrations.AlterField(
            model_name="animalcount",
            name="condition",
            field=models.CharField(
                choices=[
                    ("BA", "BAR"),
                    ("SE", "Seen"),
                    ("NA", "Attn"),
                    ("", "Not Seen"),
                ],
                default="",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="animalcount",
            name="datecounted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="groupcount",
            name="datecounted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="speciescount",
            name="datecounted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelOptions(
            name="species",
            options={"ordering": ["common_name"], "verbose_name_plural": "species"},
        ),
        migrations.AddField(
            model_name="species",
            name="class_name",
            field=models.CharField(default="none", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="species",
            name="family_name",
            field=models.CharField(default="none", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="species",
            name="order_name",
            field=models.CharField(default="none", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="species",
            name="common_name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="genus_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="species",
            name="species_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name="animal",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                populate_from=["accession_number"],
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="enclosure",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                populate_from="name",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                populate_from="accession_number",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                populate_from=["common_name", "species_name"],
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="animalcount",
            name="condition",
            field=models.CharField(
                choices=[
                    ("BA", "BAR"),
                    ("SE", "Seen"),
                    ("NA", "Attn"),
                    ("NS", "Not Seen"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterModelOptions(
            name="animalcount", options={"ordering": ["datetimecounted"]},
        ),
        migrations.AlterModelOptions(
            name="groupcount", options={"ordering": ["datetimecounted"]},
        ),
        migrations.AlterModelOptions(
            name="speciescount", options={"ordering": ["datetimecounted"]},
        ),
        migrations.RenameField(
            model_name="animalcount",
            old_name="datecounted",
            new_name="datetimecounted",
        ),
        migrations.RenameField(
            model_name="groupcount", old_name="datecounted", new_name="datetimecounted",
        ),
        migrations.RenameField(
            model_name="speciescount",
            old_name="datecounted",
            new_name="datetimecounted",
        ),
        migrations.AddField(
            model_name="animalcount",
            name="datecounted",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="animalcount",
            name="datecounted",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="groupcount",
            name="datecounted",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="groupcount",
            name="datecounted",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="speciescount",
            name="datecounted",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="speciescount",
            name="datecounted",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="animal",
            name="identifier",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="animal", name="name", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="enclosure",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="class_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="species",
            name="common_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="family_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="species",
            name="genus_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="species",
            name="order_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="species",
            name="species_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="animalcount",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("enclosures", models.ManyToManyField(to="zoo_checks.Enclosure")),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.RemoveField(model_name="enclosure", name="users",),
        migrations.AlterField(
            model_name="animal",
            name="accession_number",
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="accession_number",
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="enclosures",
            field=models.ManyToManyField(
                related_name="roles", to="zoo_checks.Enclosure"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="users",
            field=models.ManyToManyField(
                related_name="roles", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterModelOptions(
            name="animal",
            options={"ordering": [django.db.models.functions.text.Upper("name")]},
        ),
        migrations.AlterModelOptions(
            name="enclosure",
            options={"ordering": [django.db.models.functions.text.Upper("name")]},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": [
                    django.db.models.functions.text.Upper("species__common_name")
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": [django.db.models.functions.text.Upper("name")]},
        ),
        migrations.AlterModelOptions(
            name="species",
            options={
                "ordering": [django.db.models.functions.text.Upper("common_name")],
                "verbose_name_plural": "species",
            },
        ),
        migrations.AlterField(
            model_name="animal",
            name="identifier",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="animal",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="animalcount",
            name="datecounted",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.localdate
            ),
        ),
        migrations.AlterField(
            model_name="animalcount",
            name="datetimecounted",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="groupcount",
            name="datecounted",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.localdate
            ),
        ),
        migrations.AlterField(
            model_name="groupcount",
            name="datetimecounted",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="speciescount",
            name="datecounted",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.localdate
            ),
        ),
        migrations.AlterField(
            model_name="speciescount",
            name="datetimecounted",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="population_total",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="groupcount",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="groupcount",
            name="count_bar",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="groupcount",
            name="count_not_seen",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="groupcount",
            name="count_seen",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="groupcount",
            name="count_total",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="groupcount",
            name="needs_attn",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(model_name="groupcount", name="count_female",),
        migrations.RemoveField(model_name="groupcount", name="count_male",),
        migrations.RemoveField(model_name="groupcount", name="count_unknown",),
        migrations.AddField(
            model_name="role",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                populate_from="name",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="animalcount",
            name="condition",
            field=models.CharField(
                choices=[
                    ("BA", "BAR"),
                    ("SE", "Seen"),
                    ("NA", "Attn"),
                    ("NS", "Absent"),
                    ("", "Not Obs"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
