# Generated by Django 2.2.2 on 2019-06-10 01:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zoo_checks", "0013_auto_20190609_1529"),
    ]

    operations = [
        migrations.RenameModel(old_name="Exhibit", new_name="Enclosure"),
        migrations.RenameField(
            model_name="animal", old_name="exhibit", new_name="enclosure"
        ),
        migrations.RenameField(
            model_name="animalcount", old_name="exhibit", new_name="enclosure"
        ),
        migrations.RenameField(
            model_name="group", old_name="exhibit", new_name="enclosure"
        ),
        migrations.RenameField(
            model_name="groupcount", old_name="exhibit", new_name="enclosure"
        ),
        migrations.RenameField(
            model_name="speciescount", old_name="exhibit", new_name="enclosure"
        ),
    ]
