# Generated by Django 2.2.2 on 2019-06-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0014_auto_20190609_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['species']},
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
    ]
