# Generated by Django 2.2.2 on 2019-06-16 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0018_auto_20190615_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcount',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='zoo_checks.Group'),
        ),
        migrations.AlterField(
            model_name='speciescount',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='zoo_checks.Species'),
        ),
    ]
