# Generated by Django 2.2.3 on 2019-07-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0022_auto_20190625_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='class_name',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='family_name',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='order_name',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='species',
            name='common_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='genus_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_name',
            field=models.CharField(max_length=50),
        ),
    ]
