# Generated by Django 2.2.5 on 2019-10-09 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0025_auto_20190907_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalcount',
            options={'ordering': ['datetimecounted']},
        ),
        migrations.AlterModelOptions(
            name='groupcount',
            options={'ordering': ['datetimecounted']},
        ),
        migrations.AlterModelOptions(
            name='speciescount',
            options={'ordering': ['datetimecounted']},
        ),
        migrations.RenameField(
            model_name='animalcount',
            old_name='datecounted',
            new_name='datetimecounted',
        ),
        migrations.RenameField(
            model_name='groupcount',
            old_name='datecounted',
            new_name='datetimecounted',
        ),
        migrations.RenameField(
            model_name='speciescount',
            old_name='datecounted',
            new_name='datetimecounted',
        ),
    ]
