# Generated by Django 2.2.5 on 2019-10-09 02:52

from dateutil import tz
from django.db import migrations, models
from django.utils import timezone


def migrate_data_forward(Series):
    tzinfo = tz.gettz("America/New_York")
    for series in Series.objects.all().iterator():
        series.datecounted = series.datetimecounted.astimezone(tzinfo).date()
        series.save()


def migrate_data_forward_animalcount(apps, schema_editor):
    Series = apps.get_model("zoo_checks", "AnimalCount")
    migrate_data_forward(Series)


def migrate_data_forward_groupcount(apps, schema_editor):
    Series = apps.get_model("zoo_checks", "GroupCount")
    migrate_data_forward(Series)


def migrate_data_forward_speciescount(apps, schema_editor):
    Series = apps.get_model("zoo_checks", "SpeciesCount")
    migrate_data_forward(Series)


def migrate_data_backward(apps, schema_editor):
    pass  # code for reverting migration, if any


class Migration(migrations.Migration):

    dependencies = [("zoo_checks", "0026_auto_20191008_2248")]

    operations = [
        migrations.AddField(
            model_name="animalcount",
            name="datecounted",
            field=models.DateField(null=True),
        ),
        migrations.RunPython(migrate_data_forward_animalcount, migrate_data_backward),
        migrations.AlterField(
            model_name="animalcount",
            name="datecounted",
            field=models.DateField(default=timezone.localdate),
        ),
        migrations.AddField(
            model_name="groupcount",
            name="datecounted",
            field=models.DateField(null=True),
        ),
        migrations.RunPython(migrate_data_forward_groupcount, migrate_data_backward),
        migrations.AlterField(
            model_name="groupcount",
            name="datecounted",
            field=models.DateField(default=timezone.localdate),
        ),
        migrations.AddField(
            model_name="speciescount",
            name="datecounted",
            field=models.DateField(null=True),
        ),
        migrations.RunPython(migrate_data_forward_speciescount, migrate_data_backward),
        migrations.AlterField(
            model_name="speciescount",
            name="datecounted",
            field=models.DateField(default=timezone.localdate),
        ),
    ]
