# Generated by Django 2.2.8 on 2020-01-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0028_auto_20191216_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalcount',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
