# Generated by Django 2.2.9 on 2020-02-03 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0030_auto_20200127_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='accession_number',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='accession_number',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='enclosures',
            field=models.ManyToManyField(related_name='roles', to='zoo_checks.Enclosure'),
        ),
        migrations.AlterField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(related_name='roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
