# Generated by Django 2.2.9 on 2020-02-03 05:00

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0031_auto_20200202_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': [django.db.models.functions.text.Upper('name')]},
        ),
        migrations.AlterModelOptions(
            name='enclosure',
            options={'ordering': [django.db.models.functions.text.Upper('name')]},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': [django.db.models.functions.text.Upper('species__common_name')]},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': [django.db.models.functions.text.Upper('name')]},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': [django.db.models.functions.text.Upper('common_name')], 'verbose_name_plural': 'species'},
        ),
    ]
