# Generated by Django 2.2.9 on 2020-02-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0032_auto_20200203_0000'),
        ('zoo_checks', '0030_auto_20200207_2126'),
    ]

    operations = [
    ]
