# Generated by Django 2.2.9 on 2020-02-22 16:44

from django.db import migrations


def migrate_data_forward(apps, schema_editor):
    Group = apps.get_model("zoo_checks", "Group")
    GroupCount = apps.get_model("zoo_checks", "GroupCount")

    for g in Group.objects.all():
        g.population_total = (
            g.population_male + g.population_female + g.population_unknown
        )
        g.save()

    for gc in GroupCount.objects.all():
        if gc.group.active:
            gc.count_total = gc.group.population_total
            gc.count_seen = gc.count_male + gc.count_female + gc.count_unknown
            if (gc.count_total - gc.count_seen) > 0:
                gc.count_not_seen = gc.count_total - gc.count_seen
            gc.save()


class Migration(migrations.Migration):

    dependencies = [
        ("zoo_checks", "0035_auto_20200222_1052"),
    ]

    operations = [
        migrations.RunPython(migrate_data_forward),
    ]
