# Generated by Django 2.2.9 on 2020-02-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0036_convert_group_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcount',
            name='count_female',
        ),
        migrations.RemoveField(
            model_name='groupcount',
            name='count_male',
        ),
        migrations.RemoveField(
            model_name='groupcount',
            name='count_unknown',
        ),
    ]
