# Generated by Django 3.0.8 on 2020-07-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0038_role_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalcount',
            name='condition',
            field=models.CharField(choices=[('BA', 'BAR'), ('SE', 'Seen'), ('NA', 'Attn'), ('NS', 'Absent'), ('', 'Not Obs')], max_length=2, null=True),
        ),
    ]
