# Generated by Django 2.2.1 on 2019-06-02 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('zoo_checks', '0001_initial'), ('zoo_checks', '0002_auto_20190528_0217'), ('zoo_checks', '0003_auto_20190601_1535'), ('zoo_checks', '0004_auto_20190601_1557'), ('zoo_checks', '0005_auto_20190602_0318'), ('zoo_checks', '0006_auto_20190602_0434')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=80)),
                ('exhibits', models.ManyToManyField(related_name='species', to='zoo_checks.Exhibit')),
                ('latin_name', models.CharField(default='species name default', max_length=80)),
            ],
            options={
                'ordering': ['common_name'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('accession_number', models.PositiveIntegerField(unique=True)),
                ('identifier', models.CharField(max_length=40)),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='zoo_checks.Exhibit')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_checks.Species')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnimalCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_checks.Animal')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('condition', models.CharField(blank=True, choices=[('', ''), ('SE', 'seen'), ('NA', 'Needs Attention'), ('BA', 'BAR (Sr. Avic.)'), ('MI', 'Missing (Avic. only)')], default='', max_length=2)),
            ],
            options={
                'abstract': False,
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='SpeciesExhibitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('datetime', models.DateTimeField()),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_checks.Exhibit')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_checks.Species')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ['datetime'],
            },
        ),
    ]
