# Generated by Django 2.2.1 on 2019-06-06 02:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zoo_checks", "0002_auto_20190602_1402"),
    ]

    operations = [
        migrations.RenameModel(old_name="SpeciesExhibitCount", new_name="SpeciesCount")
    ]
