# Generated by Django 2.2.2 on 2019-06-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0011_auto_20190608_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalcount',
            name='condition',
            field=models.CharField(choices=[('BA', 'BAR'), ('SE', 'Seen'), ('NA', 'Attn')], max_length=2),
        ),
    ]
