# Generated by Django 2.2.2 on 2019-06-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0012_auto_20190609_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='latin_name',
            new_name='species_name',
        ),
        migrations.AddField(
            model_name='species',
            name='genus_name',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
