# Generated by Django 2.2.2 on 2019-06-16 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0017_auto_20190610_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['species__common_name']},
        ),
        migrations.AlterField(
            model_name='animalcount',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='zoo_checks.Animal'),
        ),
    ]
