# Generated by Django 2.2.2 on 2019-06-24 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0020_auto_20190617_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalcount',
            name='datecounted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupcount',
            name='datecounted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='speciescount',
            name='datecounted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
