# Generated by Django 2.2.5 on 2019-09-07 20:13

from django.db import migrations, models

from ..models import AnimalCount


def migrate_data_forward(apps, schema_editor):
    for instance in AnimalCount.objects.filter(condition=""):
        instance.condition = "NS"
        instance.save()


def migrate_data_backward(apps, schema_editor):
    for instance in AnimalCount.objects.filter(condition="NS"):
        instance.condition = ""
        instance.save()


class Migration(migrations.Migration):

    dependencies = [("zoo_checks", "0024_auto_20190829_2344")]

    operations = [
        migrations.AlterField(
            model_name="animalcount",
            name="condition",
            field=models.CharField(
                choices=[
                    ("BA", "BAR"),
                    ("SE", "Seen"),
                    ("NA", "Attn"),
                    ("NS", "Not Seen"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.RunPython(migrate_data_forward, migrate_data_backward),
    ]
