# Generated by Django 2.2.5 on 2019-12-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0027_auto_20191008_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='identifier',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enclosure',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='class_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='common_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='family_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='genus_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='order_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_name',
            field=models.CharField(max_length=100),
        ),
    ]
