# Generated by Django 2.2.9 on 2020-02-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_checks', '0029_animalcount_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='identifier',
            field=models.CharField(max_length=200),
        ),
    ]
