# Generated by Django 2.2.9 on 2020-01-28 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zoo_checks', '0029_animalcount_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enclosure',
            name='users',
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enclosures', models.ManyToManyField(to='zoo_checks.Enclosure')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
