# Generated by Django 3.0.7 on 2020-06-20 22:27

from django.db import migrations
import django_extensions.db.fields


def migrate_data_forward(apps, schema_editor):
    Role = apps.get_model("zoo_checks", "Role")

    for instance in Role.objects.all():
        print("Generating slug for %s" % instance.name)
        instance.save()  # Will trigger slug update


def migrate_data_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("zoo_checks", "0037_auto_20200222_1145"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                populate_from="name",
                unique=True,
            ),
        ),
        migrations.RunPython(migrate_data_forward, migrate_data_backward),
    ]
